
// User
export const LOAD_ALL_USER_REQUEST = 'LOAD_ALL_USER_REQUEST'
export const LOAD_ALL_USER_SUCCESS = 'LOAD_ALL_USER_SUCCESS'
export const LOAD_ALL_USER_FAILURE = 'LOAD_ALL_USER_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'
