
// User
export const LOAD_ALL_USER_REQUEST = 'LOAD_ALL_USER_REQUEST'
export const LOAD_ALL_USER_SUCCESS = 'LOAD_ALL_USER_SUCCESS'
export const LOAD_ALL_USER_FAILURE = 'LOAD_ALL_USER_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'

// Category
export const LOAD_ALL_CATEGORY_REQUEST = 'LOAD_ALL_CATEGORY_REQUEST'
export const LOAD_ALL_CATEGORY_SUCCESS = 'LOAD_ALL_CATEGORY_SUCCESS'
export const LOAD_ALL_CATEGORY_FAILURE = 'LOAD_ALL_CATEGORY_FAILURE'
